### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by noptrix** [stanislav-web/OpenDoor#16]
Hey @stanislav-web,

so I've changed the PKGBUILD to use python3 instead of python2 and I am getting the following runtime error on ArchLinux (BlackArch) with kernel 4.11.3 + python3.6 + all required dependencies:

`$ opendoor 
Traceback (most recent call last):
  File "/usr/bin/opendoor", line 11, in <module>
    load_entry_point('opendoor==3.3.36rc0', 'console_scripts', 'opendoor')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2649, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2303, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/src/__init__.py", line 21, in <module>
    from .controller import Controller
  File "/usr/lib/python3.6/site-packages/src/controller.py", line 19, in <module>
    from src.core.decorators import execution_time
  File "/usr/lib/python3.6/site-packages/src/core/__init__.py", line 43, in <module>
    from .logger import LoggerException as exception
  File "/usr/lib/python3.6/site-packages/src/core/logger/__init__.py", line 19, in <module>
    from .exception import LoggerException
  File "/usr/lib/python3.6/site-packages/src/core/logger/exception.py", line 24, in <module>
    from .config import Config
  File "/usr/lib/python3.6/site-packages/src/core/logger/config.py", line 34, in <module>
    class Config(object):
  File "/usr/lib/python3.6/site-packages/src/core/logger/config.py", line 38, in Config
    logdir = os.path.dirname(exception_log())
  File "/usr/lib/python3.6/site-packages/src/core/logger/config.py", line 30, in exception_log
    config = filesystem.readcfg('setup.cfg')
  File "/usr/lib/python3.6/site-packages/src/core/filesystem/filesystem.py", line 259, in readcfg
    os.chdir(cwd.group())
AttributeError: 'NoneType' object has no attribute 'group'
`

The PKGBUILD file can be found here: https://github.com/BlackArch/blackarch/tree/36ebf72683990e5a4c36d7993cb28d79ffee4910/packages/opendoor

Can we solve this asap so i can release opendoor along with the new BlackArch ISOs soon?

**Comment by stanislav-web** [comment]
Hi, noptrix ! Could you fetch my hotfix ?
I hope there will not be problems

**Comment by stanislav-web** [comment]
Closed. This issue has been resolved
