### ISSUE TITLE
Fix ImportError: cannot import name 'DependencyWarning' OpenDoor

### ISSUE THREAD

**Issue by gagaltotal** [stanislav-web/OpenDoor#28]
Traceback (most recent call last):
  File "./opendoor.py", line 32, in <module>
    from src import Controller, SrcError
  File "/home/ghostgtr666/Documents/tools/OpenDoor/src/__init__.py", line 21, in <module>
    from .controller import Controller
  File "/home/ghostgtr666/Documents/tools/OpenDoor/src/controller.py", line 19, in <module>
    from src.core.decorators import execution_time
  File "/home/ghostgtr666/Documents/tools/OpenDoor/src/core/__init__.py", line 31, in <module>
    from .http import HttpRequest as request_http
  File "/home/ghostgtr666/Documents/tools/OpenDoor/src/core/http/__init__.py", line 20, in <module>
    from .proxy import Proxy
  File "/home/ghostgtr666/Documents/tools/OpenDoor/src/core/http/proxy.py", line 23, in <module>
    from urllib3.exceptions import DependencyWarning, MaxRetryError, ProxySchemeUnknown,\
ImportError: cannot import name 'DependencyWarning'

how to fix just type this command
and simply upgrade the package on the pip
> $ sudo pip install --upgrade requests

run opendoor
> python opendoor.py

more or less please check the documentation from me
> https://www.gagaltotal666.site/2018/09/mengatasi-importerror-dependencywarning.html

and apologize if the documentation is different language
please use translate if you don't know the language I use in the documentation
so and hopefully useful ^_^

**Comment by stanislav-web** [comment]
Thank you @gagaltotal
