### ISSUE TITLE
Exeption in thread

### ISSUE THREAD

**Issue by Nassz** [stanislav-web/OpenDoor#3]
Hi, I have faced with issue :  
-------
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/threadpool.py", line 150, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
-------
root@123:~/OpenDoor# python --version
Python 2.7.9

**Comment by stanislav-web** [comment]
Already fixed on main branch! The project is under redesign
