### ISSUE TITLE
pip install -r requirements.txt -- [!] Several dependencies wasn't installed!

### ISSUE THREAD

**Issue by erin-bristow** [stanislav-web/OpenDoor#43]
Hello, I have tried both `sudo pip install -r requirements.txt` and `pip install -r requirements.txt` but I am still getting errors. Any help would be appreciated!

```
python3 opendoor.py --host https://somesite.com
Traceback (most recent call last):
  File "opendoor.py", line 25, in <module>
    __import__(_)
ModuleNotFoundError: No module named 'json2html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "opendoor.py", line 27, in <module>
    sys.exit("""\t\t[!] Several dependencies wasn't installed! Please run pip install -r requirements.txt. Details : %s.""" %(error))
NameError: name 'error' is not defined
```

When I try to do `pip install -r requirements.txt`:
```
pip install -r requirements.txt
Collecting urllib3 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/9f/f0/a391d1463ebb1b233795cabfc0ef38d3db4442339de68f847026199e69d7/urllib3-1.25.10-py2.py3-none-any.whl
Collecting json2html (from -r requirements.txt (line 2))
Collecting tabulate (from -r requirements.txt (line 3))
Installing collected packages: urllib3, json2html, tabulate
Successfully installed json2html-1.3.0 tabulate-0.8.7 urllib3-1.25.10
```

**Comment by stanislav-web** [comment]
@erin-bristow try run via ```pip3 install -r requirements.txt```
