### ISSUE TITLE
Not Working at all

### ISSUE THREAD

**Issue by Pessword** [stanislav-web/OpenDoor#58]
Traceback (most recent call last):
  File "/root/OpenDoor/opendoor.py", line 35, in <module>
    bootstrap = Controller()
                ^^^^^^^^^^^^
  File "/root/OpenDoor/src/controller.py", line 54, in __init__
    self.ioargs = args().get_arguments()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/OpenDoor/src/lib/io/arguments.py", line 37, in get_arguments
    args = options().get_arg_values()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/OpenDoor/src/core/options/options.py", line 387, in get_arg_values
    args = Filter.filter(args)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/OpenDoor/src/core/options/filter.py", line 45, in filter
    filtered['host'] = Filter.host(value)
                       ^^^^^^^^^^^^^^^^^^
  File "/root/OpenDoor/src/core/options/filter.py", line 95, in host
    regex = re.compile(r"" + Filter.URL_REGEX + "")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 980, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 863, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 455, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 841, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 69

**Comment by brustver** [comment]
please see https://github.com/stanislav-web/OpenDoor/issues/57 solution

**Comment by stanislav-web** [comment]
Fixed
